#############################################################################
# Makefile for building: 03-splatterBoardManip
# Generated by qmake (1.07a) (Qt 3.3.8b) on: Fri Jul 30 12:39:11 2010
# Project:  03-splatterBoardManip.pro
# Template: app
# Command: $(QMAKE) -o Makefile 03-splatterBoardManip.pro
#############################################################################

####### Compiler, tools and options

CC       = gcc
CXX      = g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -g -Wall -W -O2 -D_REENTRANT  -DQT_NO_DEBUG -DQT_THREAD_SUPPORT -DQT_SHARED -DQT_TABLET_SUPPORT
CXXFLAGS = -pipe -g -Wall -W -O2 -D_REENTRANT  -DQT_NO_DEBUG -DQT_THREAD_SUPPORT -DQT_SHARED -DQT_TABLET_SUPPORT
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I/usr/share/qt3/mkspecs/default -I. -I. -I/usr/include/qt3 -I/usr/X11R6/include -I/usr/X11R6/include
LINK     = g++
LFLAGS   = 
LIBS     = $(SUBLIBS) -L/usr/share/qt3/lib -L/usr/X11R6/lib -L/usr/X11R6/lib -lqt-mt -lGLU -lGL -lXmu -lXext -lX11 -lm -lpthread
AR       = ar cqs
RANLIB   = 
MOC      = /usr/share/qt3/bin/moc
UIC      = /usr/share/qt3/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY)
COPY_DIR = $(COPY) -r
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p

####### Output directory

OBJECTS_DIR = ./

####### Files

HEADERS = splatterBoardManip.h
SOURCES = main.cpp \
		splatterBoardManip.cpp
OBJECTS = main.o \
		splatterBoardManip.o
FORMS = 
UICDECLS = 
UICIMPLS = 
SRCMOC   = moc_splatterBoardManip.cpp
OBJMOC = moc_splatterBoardManip.o
DIST	   = 03-splatterBoardManip.pro
QMAKE_TARGET = 03-splatterBoardManip
DESTDIR  = 
TARGET   = 03-splatterBoardManip

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(OBJCOMP) $(LIBS)

mocables: $(SRCMOC)
uicables: $(UICDECLS) $(UICIMPLS)

$(MOC): 
	( cd $(QTDIR)/src/moc && $(MAKE) )

Makefile: 03-splatterBoardManip.pro  /usr/share/qt3/mkspecs/default/qmake.conf /usr/share/qt3/lib/libqt-mt.prl
	$(QMAKE) -o Makefile 03-splatterBoardManip.pro
qmake: 
	@$(QMAKE) -o Makefile 03-splatterBoardManip.pro

dist: 
	@mkdir -p .tmp/03-splatterBoardManip && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) .tmp/03-splatterBoardManip/ && ( cd `dirname .tmp/03-splatterBoardManip` && $(TAR) 03-splatterBoardManip.tar 03-splatterBoardManip && $(GZIP) 03-splatterBoardManip.tar ) && $(MOVE) `dirname .tmp/03-splatterBoardManip`/03-splatterBoardManip.tar.gz . && $(DEL_FILE) -r .tmp/03-splatterBoardManip

mocclean:
	-$(DEL_FILE) $(OBJMOC)
	-$(DEL_FILE) $(SRCMOC)

uiclean:

yaccclean:
lexclean:
clean: mocclean
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) $(TARGET)


FORCE:

####### Compile

main.o: main.cpp splatterBoardManip.h

splatterBoardManip.o: splatterBoardManip.cpp splatterBoardManip.h

moc_splatterBoardManip.o: moc_splatterBoardManip.cpp  splatterBoardManip.h 

moc_splatterBoardManip.cpp: $(MOC) splatterBoardManip.h
	$(MOC) splatterBoardManip.h -o moc_splatterBoardManip.cpp

####### Install

install:  

uninstall:  

