######################################################################
# Automatically generated by qmake (1.07a) Fri Jul 30 11:09:41 2010
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Config
CONFIG += qt opengl

# Input
HEADERS += splatterBoardManip.h
SOURCES += main.cpp splatterBoardManip.cpp
